[build-dependencies]
regex = "1.11.1"

[build-dependencies.bindgen]
default-features = false
features = ["runtime", "which-rustfmt"]
optional = true
version = "0.71"

[build-dependencies.cc]
features = ["parallel"]
version = "1.2.17"

[build-dependencies.pkg-config]
version = "0.3.32"

[features]
debug = [] # Enable zstd debug logs
default = ["legacy", "zdict_builder", "bindgen"]
experimental = [] # Expose experimental ZSTD API
fat-lto = []  # Enable fat-lto, will override thin-lto if specified
legacy = [] # Enable legacy ZSTD support (for versions < zstd-0.8)
no_asm = [] # Disable ASM files (only on amd64 for decompression)
no_wasm_shim = [
] # Disable wasm shims (in case your wasm toolchain includes a C stdlib).
non-cargo = [] # Silence cargo-specific build flags
pkg-config = [] # Use pkg-config to build the zstd C library.
seekable = [] # Enable support of the seekable format
std = [] # Deprecated: we never use types from std.
thin = [] # Optimize binary by size
thin-lto = [] # Enable thin-lto, will fallback to fat-lto if not supported
zdict_builder = [
] # Enable dictionary building (dictionary _using_ is always supported).
zstdmt = [] # Enable multi-thread support (with pthread)

[lib]
doctest = false # Documentation is for C code, good luck testing that.
path = "src/lib.rs"

[lints]

[lints.rust]
non_upper_case_globals = "allow"

[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
categories = ["api-bindings", "compression"]
description = "Low-level bindings for the zstd compression library."
edition = "2018"
include = [
	"/LICENSE*",
	"!/*.sh",
	"/build.rs",
	"/*.h",
	"/src/",
	"/wasm-shim/**/*.h",
	"/zstd/LICENSE",
	"/zstd/COPYING",
	"/zstd/lib/**/*.c",
	"/zstd/lib/**/*.h",
	"/zstd/lib/**/*.S",
	"/zstd/contrib/seekable_format/*.c",
	"/zstd/contrib/seekable_format/*.h",
]
keywords = ["zstd", "zstandard", "compression"]
license = "MIT/Apache-2.0"
links = "zstd"
name = "zstd-sys"
readme = "Readme.md"
repository = "https://github.com/gyscos/zstd-rs"
rust-version = "1.89.0"
version = "2.0.15+zstd.1.5.7"

[package.metadata]

[package.metadata.docs]

[package.metadata.docs.rs]
features = ["experimental"]
