[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
categories = [
    "api-bindings",
    "compression",
]
description = "Low-level bindings for the zstd compression library."
keywords = [
    "zstd",
    "zstandard",
    "compression",
]
license = "MIT/Apache-2.0"
links = "zstd"
name = "zstd-sys"
readme = "Readme.md"
repository = "https://github.com/gyscos/zstd-rs"
version ="1.4.6+zstd.1.3.7"

[build-dependencies]
blob = "0.2.0"
glob = "0.2.11"

[build-dependencies.bindgen]
optional = true
version = "0.43"

[build-dependencies.cc]
version = "1.0"
features = ["parallel"]


[dependencies]
libc = "0.2.21"

[dev-dependencies]
libc = "0.2.42"

[features]
default = ["legacy"]
legacy = []
zstdmt = []
std = ["bindgen"]
