[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
zstd-safe = { path = "zstd-safe", version = "7.1.0", default-features = false, features = [
	"std",
] }

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
humansize = "2.0"
partial-io = "0.5"
walkdir = "2.2"

[[example]]
name = "train"
required-features = ["zdict_builder"]

[features]
arrays = ["zstd-safe/arrays"]
bindgen = ["zstd-safe/bindgen"]
debug = ["zstd-safe/debug"]
default = ["legacy", "arrays", "zdict_builder"]
doc-cfg = []
experimental = ["zstd-safe/experimental"]
fat-lto = ["zstd-safe/fat-lto"]
legacy = ["zstd-safe/legacy"]
no_asm = ["zstd-safe/no_asm"]
pkg-config = ["zstd-safe/pkg-config"]
thin = ["zstd-safe/thin"]
thin-lto = ["zstd-safe/thin-lto"]
wasm = []
zdict_builder = ["zstd-safe/zdict_builder"]
zstdmt = ["zstd-safe/zstdmt"]

[lib]
path = "src/lib.rs"

[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["compression", "api-bindings"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
edition = "2018"
exclude = ["assets/*.zst", "/.github"]
keywords = ["zstd", "zstandard", "compression"]
license = "MIT"
name = "zstd"
readme = "Readme.md"
repository = "https://github.com/gyscos/zstd-rs"
rust-version = "1.64"
version = "0.13.3"

[package.metadata]

[package.metadata.docs]

[package.metadata.docs.rs]
features = ["experimental", "zstdmt", "zdict_builder", "doc-cfg"]
