[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
keywords = ["zstd", "zstandard", "compression"]
categories = ["compression", "api-bindings"]
license = "MIT"
name = "zstd"
repository = "https://github.com/gyscos/zstd-rs"
version = "0.9.0+zstd.1.5.0"
exclude = ["assets/*.zst"]
readme = "Readme.md"
edition = "2018"

[package.metadata.docs.rs]
features = ["experimental"]

[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
zstd-safe = { path = "./zstd-safe", version = "=4.1.1", default-features = false, features=["std"]}

[dev-dependencies]
clap = "2.0"
humansize = "1.0"
partial-io = "0.5"
walkdir = "2.2"

[features]
default = ["legacy"]

bindgen = ["zstd-safe/bindgen"]
debug = ["zstd-safe/debug"]
legacy = ["zstd-safe/legacy"]
pkg-config = ["zstd-safe/pkg-config"]
wasm = []
zstdmt = ["zstd-safe/zstdmt"]
experimental = ["zstd-safe/experimental"]
thin = ["zstd-safe/thin"]
