[[bin]]
bench = false
doc = false
name = "zstd_fuzzer"
path = "fuzz_targets/zstd_fuzzer.rs"
test = false

[dependencies]
libfuzzer-sys = "0.4"
zstd-sys = { path = "../zstd-sys", version = "2.0.10", default-features = false }

[dependencies.zstd-safe]
path = ".."

[features]
std = ["zstd-sys/std"]

[package]
edition = "2018"
name = "zstd-safe-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[package.metadata.docs]

[package.metadata.docs.rs]
features = ["std"]
