[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "zstd-safe"
version ="1.4.7+zstd.1.3.8"
description = "Safe low-level bindings for the zstd compression library."
keywords = ["zstd", "zstandard", "compression"]
categories = ["api-bindings", "compression"]
repository = "https://github.com/gyscos/zstd-rs"
license = "MIT/Apache-2.0"
readme = "Readme.md"

[dependencies]
zstd-sys = { path="zstd-sys", version = "1.4.7", default-features = false }
libc = "0.2.21"

[features]
default = ["legacy"]
legacy = ["zstd-sys/legacy"]
bindgen = ["zstd-sys/bindgen"]
zstdmt = ["zstd-sys/zstdmt"]
std = ["zstd-sys/std"] # Use std instead of libc types - useful on wasm.
