[dependencies]
zstd-sys = { path = "zstd-sys", version = "2.0.15", default-features = false }

[features]
arrays = []
bindgen = ["zstd-sys/bindgen"]
debug = ["zstd-sys/debug"]
default = ["legacy", "arrays", "zdict_builder"]
doc-cfg = []
experimental = ["zstd-sys/experimental"]
fat-lto = ["zstd-sys/fat-lto"]
legacy = ["zstd-sys/legacy"]
no_asm = ["zstd-sys/no_asm"]
pkg-config = ["zstd-sys/pkg-config"]
seekable = ["zstd-sys/seekable"]
std = ["zstd-sys/std"]                     # Implements WriteBuf for std types like Cursor and Vec.
thin = ["zstd-sys/thin"]
thin-lto = ["zstd-sys/thin-lto"]
zdict_builder = ["zstd-sys/zdict_builder"]
zstdmt = ["zstd-sys/zstdmt"]

[lib]
path = "src/lib.rs"

[lints]

[lints.rust]
non_upper_case_globals = "allow"

[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
categories = ["api-bindings", "compression"]
description = "Safe low-level bindings for the zstd compression library."
edition = "2018"
exclude = ["update_consts.sh"]
keywords = ["zstd", "zstandard", "compression"]
license = "MIT OR Apache-2.0"
name = "zstd-safe"
readme = "Readme.md"
repository = "https://github.com/gyscos/zstd-rs"
rust-version = "1.89.0"
version = "7.2.4"

[package.metadata]

[package.metadata.docs]

[package.metadata.docs.rs]
features = ["experimental", "arrays", "std", "zdict_builder", "doc-cfg"]
